
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getStatus() : Promise<Result<StatusView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistory(query: string, offset: number, limit: number) : Promise<Result<HistoryPageView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history", { query, offset, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getImagePreview(contentId: string) : Promise<Result<ImagePreviewView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_image_preview", { contentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistory(contentId: string, action: HistoryUpdateView) : Promise<Result<MutationView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history", { contentId, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPeers() : Promise<Result<PeersView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_peers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<SettingsView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDiagnostics() : Promise<Result<DiagnosticView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTransfers() : Promise<Result<TransferView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transfers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelTransfer(transferId: string) : Promise<Result<MutationView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_transfer", { transferId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async forgetDevice(deviceId: string) : Promise<Result<MutationView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forget_device", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSharedSetting(setting: SharedSettingView, value: number) : Promise<Result<MutationView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_shared_setting", { setting, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePeerInterfaces(interfaces: string[]) : Promise<Result<MutationView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_peer_interfaces", { interfaces }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activateHistory(contentId: string) : Promise<Result<MutationView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_history", { contentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type DeviceView = { deviceId: string; local: boolean; forgotten: boolean }
export type DiagnosticView = { name: string; ok: boolean; detail: string }
export type HistoryItemView = { contentId: string; preview: string; mimeTypes: string[]; logicalSize: number; sourceNode: string; sourceDevice: string; pinned: boolean; physicalMillis: number; originMillis: number | null }
export type HistoryPageView = { items: HistoryItemView[]; total: number }
export type HistoryUpdateView = "pin" | "unpin" | "delete"
export type ImagePreviewView = { contentId: string; mimeType: string; width: number; height: number; rgba: number[] }
export type LocalSettingsView = { listenPort: number; discoveryIntervalSeconds: number; reconcileIntervalSeconds: number; reconnectMinSeconds: number; reconnectMaxSeconds: number; peerInterfaces: string[]; meshKeyFileConfigured: boolean; configPath: string }
export type MutationView = { ok: boolean; message: string; resourceId: string | null }
export type PeerStatsView = { sharedItems: number; sharedBytes: number; pinnedItems: number; lastSharedMillis: number | null }
export type PeerView = { hostname: string; address: string; connected: boolean; stats: PeerStatsView | null }
export type PeersView = { localHostname: string; localAddresses: string[]; peers: PeerView[]; discoveryError: string | null; devices: DeviceView[] }
export type SettingsView = { shared: SharedSettingsView; local: LocalSettingsView }
export type SharedSettingView = "meshQuotaBytes" | "captureThresholdBytes"
export type SharedSettingsView = { meshQuotaBytes: number; captureThresholdBytes: number; revision: string }
export type StatusView = { version: string; hostname: string; uptimeSeconds: number; configPath: string; localAddresses: string[]; discoveredPeers: number; connectedPeers: number }
export type TransferView = { transferId: string; contentId: string; peer: string; state: string; completedBytes: number; totalBytes: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
