import { describe, expect, it } from 'vitest';

import {
	activateHistory,
	getDiagnostics,
	getHistory,
	getImagePreview,
	getPeers,
	getSettings,
	getStatus,
	getTransfers,
	isTauri,
	updateHistory
} from './bridge';

describe('browser preview bridge', () => {
	it('is clearly separate from the Tauri IPC runtime', async () => {
		expect(isTauri()).toBe(false);
		await expect(getStatus()).resolves.toMatchObject({
			version: 'preview',
			hostname: 'browser-preview'
		});
	});

	it('provides a bounded raster preview for the sample image', async () => {
		const preview = await getImagePreview('preview-image');

		expect(preview).toMatchObject({
			contentId: 'preview-image',
			mimeType: 'image/png',
			width: 96,
			height: 60
		});
		expect(preview.rgba).toHaveLength(preview.width * preview.height * 4);
	});

	it('supports representative search and activation without real clipboard data', async () => {
		const page = await getHistory('kiwi', 0, 2);
		expect(page.total).toBe(1);
		expect(page.items).toHaveLength(1);
		const item = page.items[0];
		expect(item?.sourceDevice).toBe('kiwi');
		if (!item) throw new Error('expected one browser preview history item');

		await expect(activateHistory(item.contentId)).resolves.toEqual({
			ok: true,
			message: 'Preview activation simulated',
			resourceId: item.contentId
		});
	});

	it('supports the source filter generated by the history context menu', async () => {
		const page = await getHistory('device:"vd"', 0, 10);

		expect(page.total).toBe(2);
		expect(page.items.every((item) => item.sourceDevice === 'vd')).toBe(true);
	});

	it('provides non-sensitive management previews', async () => {
		await expect(getPeers()).resolves.toMatchObject({
			localHostname: 'browser-preview',
			peers: expect.any(Array)
		});
		await expect(getSettings()).resolves.toMatchObject({
			local: { configPath: 'Browser preview — no local configuration' }
		});
		await expect(getDiagnostics()).resolves.toEqual(expect.any(Array));
		await expect(getTransfers()).resolves.toEqual([]);
	});

	it('returns only the requested browser-preview page', async () => {
		const firstPage = await getHistory('', 0, 2);
		const secondPage = await getHistory('', 2, 2);

		expect(firstPage).toMatchObject({ total: 3 });
		expect(firstPage.items).toHaveLength(2);
		expect(secondPage).toMatchObject({ total: 3 });
		expect(secondPage.items.map((item) => item.contentId)).toEqual(['preview-image']);
	});

	it('simulates pinning without exposing a real clipboard', async () => {
		await expect(updateHistory('preview-docs-url', 'pin')).resolves.toMatchObject({ ok: true });
		expect((await getHistory('kiwi', 0, 2)).items[0]?.pinned).toBe(true);
		await updateHistory('preview-docs-url', 'unpin');
	});
});
